repo_name: OshinoShinobuLinux-Chan/-shell-Tutorial
repo_url: https://github.com/OshinoShinobu-Chan/Linux-shell-Tutorial
site_author: OshinoShinobu-Chan
site_descrption: 这是一个关于如何更好地使用linux shell的教程
site_name: Linux shell Tutorial
site_url: https://oshinoshinobu-chan.github.io/Linux-shell-Tutorial/
use_directory_urls: false
theme:
  font:
    code: Fira Mono
  language: zh
  name: material
  custom_dir: overrides
  palette:
  - accent: light blue
    media: '(prefers-color-scheme: light)'
    primary: white
    scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - accent: light blue
    media: '(prefers-color-scheme: dark)'
    primary: light grey
    scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
extra:
  analytics:
    provider: google
    property: G-T87G1452XL
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OshinoShinobu-Chan
      # name: GitHub
    - icon: fontawesome/regular/envelope
      link: mailto:2200012909@stu.pku.edu.cn
  generator: false
copyright: "Linux shell Turorial © 2024 by OshinoShinobu-Chan is licensed under CC BY-NC 4.0"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
plugins:
   - glightbox
   - search
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js